<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KawasakiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $hondaId = DB::table('brand_names')->where('name', 'Kawasaki')->first()->id;

        $bikeModels = [
            ['model' => 'AN110'],
            ['model' => 'AR50'],
            ['model' => 'AR80'],
            ['model' => 'AR125'],
            ['model' => 'EL250 ELIMINATOR'],
            ['model' => 'EL252 ELIMINATOR'],
            ['model' => 'ELIMINATOR 125'],
            ['model' => 'ELIMINATOR 250V'],
            ['model' => 'ELIMINATOR 600'],
            ['model' => 'EN500'],
            ['model' => 'ER-5'],
            ['model' => 'ER-6f'],
            ['model' => 'ER-6f ABS'],
            ['model' => 'ER-6n'],
            ['model' => 'ER-6n ABS'],
            ['model' => 'GPX600R'],
            ['model' => 'GPX750R'],
            ['model' => 'GPz305 BELT DRIVE'],
            ['model' => 'GPZ400S'],
            ['model' => 'GPZ500S'],
            ['model' => 'GPz550'],
            ['model' => 'GPZ600R'],
            ['model' => 'GPZ900R'],
            ['model' => 'GPZ1000RX'],
            ['model' => 'GPZ1100'],
            ['model' => 'GPZ1100 ABS'],
            ['model' => 'GT550'],
            ['model' => 'GT750'],
            ['model' => 'GTR 1000'],
            ['model' => 'GTR 1400 ABS'],
            ['model' => 'J125'],
            ['model' => 'J300'],
            ['model' => 'J300 ABS'],
            ['model' => 'KH125'],
            ['model' => 'KLE 500'],
            ['model' => 'KLE 650 VERSYS'],
            ['model' => 'KLX 110'],
            ['model' => 'KLX 125'],
            ['model' => 'KLX 150'],
            ['model' => 'KLX 250'],
            ['model' => 'KLX 450R'],
            ['model' => 'KLZ 1000 VERSYS'],
            ['model' => 'KR-1'],
            ['model' => 'KR-1S'],
            ['model' => 'KX 65'],
            ['model' => 'KX 85'],
            ['model' => 'KX 125'],
            ['model' => 'KX 250'],
            ['model' => 'KX 250 F'],
            ['model' => 'KX 450 F'],
            ['model' => 'KZ1000 POLICE'],
            ['model' => 'LTD450'],
            ['model' => 'NINJA 250R'],
            ['model' => 'NINJA 250SL'],
            ['model' => 'NINJA 250SL ABS'],
            ['model' => 'NINJA 300'],
            ['model' => 'NINJA 300 ABS'],
            ['model' => 'NINJA 650 ABS'],
            ['model' => 'NINJA H2'],
            ['model' => 'NINJA H2-R'],
            ['model' => 'NINJA ZX-6R'],
            ['model' => 'NINJA ZX-6R ABS'],
            ['model' => 'NINJA ZX-6RR'],
            ['model' => 'NINJA ZX-7R'],
            ['model' => 'NINJA ZX-7RR'],
            ['model' => 'NINJA ZX-9R'],
            ['model' => 'NINJA ZX-10R'],
            ['model' => 'NINJA ZX-10R ABS'],
            ['model' => 'NINJA ZX-12R'],
            ['model' => 'VERSYS-X 300 ABS'],
            ['model' => 'VERSYS 1000'],
            ['model' => 'VN-15'],
            ['model' => 'VN-15SE'],
            ['model' => 'VN750 TWIN'],
            ['model' => 'VN800'],
            ['model' => 'VN800 CLASSIC'],
            ['model' => 'VN800 DRIFTER'],
            ['model' => 'VN900 CLASSIC'],
            ['model' => 'VN900 CLASSIC LT'],
            ['model' => 'VN900 CUSTOM'],
            ['model' => 'VN1500 CLASSIC'],
            ['model' => 'VN1500 CLASSIC FI'],
            ['model' => 'VN1500 CLASSIC TOURER'],
            ['model' => 'VN1500 CLASSIC TOURER Fi'],
            ['model' => 'VN1500 DRIFTER'],
            ['model' => 'VN1500 MEAN STREAK'],
            ['model' => 'VN1600 CLASSIC'],
            ['model' => 'VN1600 CLASSIC TOURER'],
            ['model' => 'VN1600 MEAN STREAK'],
            ['model' => 'VN1700 CLASSIC TOURER ABS'],
            ['model' => 'VN1700 CLASSIS ABS'],
            ['model' => 'VN1700 VOYAGER ABS'],
            ['model' => 'VN1700 VOYAGER CUSTOM ABS'],
            ['model' => 'VN2000'],
            ['model' => 'VN2000 CLASSIC'],
            ['model' => 'VULCAN 900 CLASSIC'],
            ['model' => 'VULCAN 900 CUSTOM'],
            ['model' => 'VULCAN 1700 NOMAD ABS'],
            ['model' => 'VULCAN 1700 VOYAGER ABS'],
            ['model' => 'VULCAN_900_CLASSIC'],
            ['model' => 'VULCAN CLASSIC'],
            ['model' => 'VULCAN S'],
            ['model' => 'VULCAN S ABS'],
            ['model' => 'W650'],
            ['model' => 'W800'],
            ['model' => 'Z250 SCORPION'],
            ['model' => 'Z250 SL'],
            ['model' => 'Z250SL ABS'],
            ['model' => 'Z300 ABS'],
            ['model' => 'Z400FII'],
            ['model' => 'Z750'],
            ['model' => 'Z750 ABS'],
            ['model' => 'Z750R'],
            ['model' => 'Z750R ABS'],
            ['model' => 'Z750S'],
            ['model' => 'Z800'],
            ['model' => 'Z800 ABS'],
            ['model' => 'Z800e ABS (A2)'],
            ['model' => 'Z1000'],
            ['model' => 'Z1000 ABS'],
            ['model' => 'Z1000SX'],
            ['model' => 'Z1000SX ABS'],
            ['model' => 'Z1300'],
            ['model' => 'ZL1000'],
            ['model' => 'ZR-7'],
            ['model' => 'ZR-7S'],
            ['model' => 'ZR 550 ZEPHYR'],
            ['model' => 'ZR 750 ZEPHYR'],
            ['model' => 'ZR 1100 ZEPHYR'],
            ['model' => 'ZRX1100'],
            ['model' => 'ZRX1200'],
            ['model' => 'ZRX1200R'],
            ['model' => 'ZRX1200S'],
            ['model' => 'ZX-10'],
            ['model' => 'ZXR400'],
            ['model' => 'ZXR750'],
            ['model' => 'ZXR750R'],
            ['model' => 'ZZ-R250'],
            ['model' => 'ZZ-R600'],
            ['model' => 'ZZ-R1100'],
            ['model' => 'ZZ-R1200'],
            ['model' => 'ZZ-R1400'],
            ['model' => 'ZZ-R1400 ABS'],
        ];

        if (DB::table('bike_models')->where('brand_name_id', $hondaId)->exists()) {
            return;
        }

        foreach ($bikeModels as $bikeModel) {
            DB::table('bike_models')->insert([
                'brand_name_id' => $hondaId,
                'model' => $bikeModel['model'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
