<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductionDataSeeder extends Seeder
{
    /**
     * Seed the application's database with production data.
     * Auto-generated from production database.
     * 
     * Total tables: 143
     * Total records: 130,033
     * 
     * Usage:
     *   php artisan db:seed --class=ProductionDataSeeder
     */
    public function run(): void
    {
        $this->call(ProductionData\AccessLogsTableSeeder::class);
        $this->call(ProductionData\AgreementAccessesTableSeeder::class);
        $this->call(ProductionData\ApplicationItemsTableSeeder::class);
        $this->call(ProductionData\BackupClubMemberPurchasesTableSeeder::class);
        $this->call(ProductionData\BikeModelsTableSeeder::class);
        $this->call(ProductionData\BlogCategoriesTableSeeder::class);
        $this->call(ProductionData\BlogImagesTableSeeder::class);
        $this->call(ProductionData\BlogPostsTableSeeder::class);
        $this->call(ProductionData\BookingClosingTableSeeder::class);
        $this->call(ProductionData\BookingIssuanceItemsTableSeeder::class);
        $this->call(ProductionData\BranchesTableSeeder::class);
        $this->call(ProductionData\BrandsTableSeeder::class);
        $this->call(ProductionData\CalendarTableSeeder::class);
        $this->call(ProductionData\CategoriesTableSeeder::class);
        $this->call(ProductionData\ChannelsTableSeeder::class);
        $this->call(ProductionData\ChatbotSessionsTableSeeder::class);
        $this->call(ProductionData\ClaimMotorbikesTableSeeder::class);
        $this->call(ProductionData\ClubMemberPurchasesTableSeeder::class);
        $this->call(ProductionData\ClubMemberRedeemTableSeeder::class);
        $this->call(ProductionData\ClubMemberSpendingPaymentsTableSeeder::class);
        $this->call(ProductionData\ClubMemberSpendingsTableSeeder::class);
        $this->call(ProductionData\ClubMembersTableSeeder::class);
        $this->call(ProductionData\CompanyVehiclesTableSeeder::class);
        $this->call(ProductionData\ContactQueriesTableSeeder::class);
        $this->call(ProductionData\ContractAccessTableSeeder::class);
        $this->call(ProductionData\CustomerAddressesTableSeeder::class);
        $this->call(ProductionData\CustomerAgreementsTableSeeder::class);
        $this->call(ProductionData\CustomerAppointmentsTableSeeder::class);
        $this->call(ProductionData\CustomerAuthsTableSeeder::class);
        $this->call(ProductionData\CustomerContractsTableSeeder::class);
        $this->call(ProductionData\CustomerDocumentsTableSeeder::class);
        $this->call(ProductionData\CustomerProfilesTableSeeder::class);
        $this->call(ProductionData\DeleteRequestOtpsTableSeeder::class);
        $this->call(ProductionData\DeliveryVehicleTypesTableSeeder::class);
        $this->call(ProductionData\DiscountsTableSeeder::class);
        $this->call(ProductionData\DocumentTypesTableSeeder::class);
        $this->call(ProductionData\EcOrderItemsTableSeeder::class);
        $this->call(ProductionData\EcOrdersTableSeeder::class);
        $this->call(ProductionData\EcShippingMethodsTableSeeder::class);
        $this->call(ProductionData\FilerentalsTableSeeder::class);
        $this->call(ProductionData\FilesTableSeeder::class);
        $this->call(ProductionData\FinanceApplicationsTableSeeder::class);
        $this->call(ProductionData\InventoriesTableSeeder::class);
        $this->call(ProductionData\InventoryHistoriesTableSeeder::class);
        $this->call(ProductionData\IpRestrictionsTableSeeder::class);
        $this->call(ProductionData\JudopayCitAccessesTableSeeder::class);
        $this->call(ProductionData\JudopayCitPaymentSessionsTableSeeder::class);
        $this->call(ProductionData\JudopayMitPaymentSessionsTableSeeder::class);
        $this->call(ProductionData\JudopayMitQueuesTableSeeder::class);
        $this->call(ProductionData\JudopayOnboardingsTableSeeder::class);
        $this->call(ProductionData\JudopayPaymentSessionOutcomesTableSeeder::class);
        $this->call(ProductionData\JudopaySubscriptionsTableSeeder::class);
        $this->call(ProductionData\LegalsTableSeeder::class);
        $this->call(ProductionData\MakesTableSeeder::class);
        $this->call(ProductionData\MediaTableSeeder::class);
        $this->call(ProductionData\ModelHasPermissionsTableSeeder::class);
        $this->call(ProductionData\ModelHasRolesTableSeeder::class);
        $this->call(ProductionData\MotCheckerTableSeeder::class);
        $this->call(ProductionData\MotorbikeAnnualComplianceTableSeeder::class);
        $this->call(ProductionData\MotorbikeDeliveryOrderEnquiriesTableSeeder::class);
        $this->call(ProductionData\MotorbikeMaintenanceLogsTableSeeder::class);
        $this->call(ProductionData\MotorbikeRegistrationsTableSeeder::class);
        $this->call(ProductionData\MotorbikeRepairObservationsTableSeeder::class);
        $this->call(ProductionData\MotorbikeRepairServicesListsTableSeeder::class);
        $this->call(ProductionData\MotorbikeRepairUpdatesTableSeeder::class);
        $this->call(ProductionData\MotorbikeSaleLogsTableSeeder::class);
        $this->call(ProductionData\MotorbikesTableSeeder::class);
        $this->call(ProductionData\MotorbikesCatBTableSeeder::class);
        $this->call(ProductionData\MotorbikesRepairTableSeeder::class);
        $this->call(ProductionData\MotorcyclesTableSeeder::class);
        $this->call(ProductionData\NewMotorbikesTableSeeder::class);
        $this->call(ProductionData\NgnCampaignReferralsTableSeeder::class);
        $this->call(ProductionData\NgnCampaignsTableSeeder::class);
        $this->call(ProductionData\NgnCareersTableSeeder::class);
        $this->call(ProductionData\NgnDigitalInvoiceItemsTableSeeder::class);
        $this->call(ProductionData\NgnDigitalInvoicesTableSeeder::class);
        $this->call(ProductionData\NgnMitQueuesTableSeeder::class);
        $this->call(ProductionData\NgnMotNotifierTableSeeder::class);
        $this->call(ProductionData\NgnPartnersTableSeeder::class);
        $this->call(ProductionData\NgnProductImagesTableSeeder::class);
        $this->call(ProductionData\NgnStockMovementsTableSeeder::class);
        $this->call(ProductionData\NgnSuperCategoriesTableSeeder::class);
        $this->call(ProductionData\NgnSurveyAnswersTableSeeder::class);
        $this->call(ProductionData\NgnSurveyOptionsTableSeeder::class);
        $this->call(ProductionData\NgnSurveyQuestionsTableSeeder::class);
        $this->call(ProductionData\NgnSurveyResponsesTableSeeder::class);
        $this->call(ProductionData\NgnSurveysTableSeeder::class);
        $this->call(ProductionData\NotesTableSeeder::class);
        $this->call(ProductionData\OtpVerificationsTableSeeder::class);
        $this->call(ProductionData\OxfordProductsTableSeeder::class);
        $this->call(ProductionData\OxfordsTableSeeder::class);
        $this->call(ProductionData\PasswordResetTokensTableSeeder::class);
        $this->call(ProductionData\PaymentMethodsTableSeeder::class);
        $this->call(ProductionData\PaymentsPaypalTableSeeder::class);
        $this->call(ProductionData\PaypalWebhookEventsTableSeeder::class);
        $this->call(ProductionData\PcnCaseUpdatesTableSeeder::class);
        $this->call(ProductionData\PcnCasesTableSeeder::class);
        $this->call(ProductionData\PcnEmailJobsTableSeeder::class);
        $this->call(ProductionData\PcnTolRequestsTableSeeder::class);
        $this->call(ProductionData\PermissionsTableSeeder::class);
        $this->call(ProductionData\PersonalAccessTokensTableSeeder::class);
        $this->call(ProductionData\ProductHasRelationsTableSeeder::class);
        $this->call(ProductionData\PurchaseAgreementAccessesTableSeeder::class);
        $this->call(ProductionData\PurchaseRequestItemsTableSeeder::class);
        $this->call(ProductionData\PurchaseRequestsTableSeeder::class);
        $this->call(ProductionData\RecoveredMotorbikesTableSeeder::class);
        $this->call(ProductionData\RentalPaymentsTableSeeder::class);
        $this->call(ProductionData\RentalTerminateAccessesTableSeeder::class);
        $this->call(ProductionData\RentalsTableSeeder::class);
        $this->call(ProductionData\RentingBookingsTableSeeder::class);
        $this->call(ProductionData\RentingOtherChargesTableSeeder::class);
        $this->call(ProductionData\RentingOtherChargesTransactionsTableSeeder::class);
        $this->call(ProductionData\RentingPricingsTableSeeder::class);
        $this->call(ProductionData\RentingServiceVideosTableSeeder::class);
        $this->call(ProductionData\RepairUpdateServiceTableSeeder::class);
        $this->call(ProductionData\RequirementSetsTableSeeder::class);
        $this->call(ProductionData\RequirementsTableSeeder::class);
        $this->call(ProductionData\RoleHasPermissionsTableSeeder::class);
        $this->call(ProductionData\RoleUsersTableSeeder::class);
        $this->call(ProductionData\RolesTableSeeder::class);
        $this->call(ProductionData\ServiceBookingsTableSeeder::class);
        $this->call(ProductionData\SmsMessagesTableSeeder::class);
        $this->call(ProductionData\StockLogsTableSeeder::class);
        $this->call(ProductionData\SurveyEmailCampaignsTableSeeder::class);
        $this->call(ProductionData\SystemCountriesTableSeeder::class);
        $this->call(ProductionData\SystemCurrenciesTableSeeder::class);
        $this->call(ProductionData\SystemSettingsTableSeeder::class);
        $this->call(ProductionData\TransactionTypesTableSeeder::class);
        $this->call(ProductionData\UploadDocumentAccessesTableSeeder::class);
        $this->call(ProductionData\UploadTestsTableSeeder::class);
        $this->call(ProductionData\UserAddressesTableSeeder::class);
        $this->call(ProductionData\UserSessionsTableSeeder::class);
        $this->call(ProductionData\UserrolesTableSeeder::class);
        $this->call(ProductionData\UsersTableSeeder::class);
        $this->call(ProductionData\UsersOldTableSeeder::class);
        $this->call(ProductionData\VehNotificationsTableSeeder::class);
        $this->call(ProductionData\VehicleDeliveryOrdersTableSeeder::class);
        $this->call(ProductionData\VehicleDeliveryOrdersItemsTableSeeder::class);
        $this->call(ProductionData\VehicleDeliveryRatesTableSeeder::class);
        $this->call(ProductionData\VehicleDeliverySurchargesTableSeeder::class);
        $this->call(ProductionData\VehicleEstimatorsTableSeeder::class);
        $this->call(ProductionData\VehicleIssuancesTableSeeder::class);
        $this->call(ProductionData\VehicleProfilesTableSeeder::class);
        $this->call(ProductionData\BookingInvoicesTableSeeder::class);
        $this->call(ProductionData\ContactsTableSeeder::class);
        $this->call(ProductionData\CustomersTableSeeder::class);
        $this->call(ProductionData\DsOrdersTableSeeder::class);
        $this->call(ProductionData\DsOrderItemsTableSeeder::class);
        $this->call(ProductionData\EcPaymentMethodsTableSeeder::class);
        $this->call(ProductionData\MotorbikesSaleTableSeeder::class);
        $this->call(ProductionData\MotorbikesSoldTableSeeder::class);
        $this->call(ProductionData\MotBookingsTableSeeder::class);
        $this->call(ProductionData\NgnBrandsTableSeeder::class);
        $this->call(ProductionData\NgnCategoriesTableSeeder::class);
        $this->call(ProductionData\NgnModelsTableSeeder::class);
        $this->call(ProductionData\NgnProductsTableSeeder::class);
        $this->call(ProductionData\PurchaseUsedVehiclesTableSeeder::class);
        $this->call(ProductionData\RentingBookingItemsTableSeeder::class);
        $this->call(ProductionData\RentingTransactionsTableSeeder::class);
    }
}
