<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SuzukiModelsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $hondaId = DB::table('brand_names')->where('name', 'Suzuki')->first()->id;

        $bikeModels = [
            ['model' => 'AN125'],
            ['model' => 'AN150'],
            ['model' => 'AN250 BURGMAN'],
            ['model' => 'AN400 ABS BURGMAN'],
            ['model' => 'AN400 BURGMAN'],
            ['model' => 'AN400Z ABS BURGMAN'],
            ['model' => 'AN650 BURGMAN'],
            ['model' => 'AN650Z ABS BURGMAN EXECUTIVE'],
            ['model' => 'AP50'],
            ['model' => 'AY50'],
            ['model' => 'AY50A'],
            ['model' => 'AY50W'],
            ['model' => 'AY50WR'],
            ['model' => 'DL650 ABS V-STROM'],
            ['model' => 'DL 650 V-STROM'],
            ['model' => 'DL650 V-STROM'],
            ['model' => 'DL650X ABS V-STROM'],
            ['model' => 'DL1000 ABS V-STROM'],
            ['model' => 'DL 1000 V-STROM'],
            ['model' => 'DR-Z70'],
            ['model' => 'DR-Z110'],
            ['model' => 'DR-Z125'],
            ['model' => 'DR-Z125L'],
            ['model' => 'DR-Z400S'],
            ['model' => 'DR-Z400SM'],
            ['model' => 'DR125S'],
            ['model' => 'DR125SE'],
            ['model' => 'DR125SM'],
            ['model' => 'DR200'],
            ['model' => 'DR250'],
            ['model' => 'DR350S'],
            ['model' => 'DR350SE'],
            ['model' => 'DR350X'],
            ['model' => 'DR400'],
            ['model' => 'DR500'],
            ['model' => 'DR600R'],
            ['model' => 'DR650R'],
            ['model' => 'DR650RE'],
            ['model' => 'DR650RS'],
            ['model' => 'DR650S'],
            ['model' => 'DR750'],
            ['model' => 'DR800'],
            ['model' => 'GN125'],
            ['model' => 'GN125E'],
            ['model' => 'GN250'],
            ['model' => 'GP100'],
            ['model' => 'GP125'],
            ['model' => 'GS250'],
            ['model' => 'GS400'],
            ['model' => 'GS425'],
            ['model' => 'GS450'],
            ['model' => 'GS500'],
            ['model' => 'GS550 KATANA'],
            ['model' => 'GS550E'],
            ['model' => 'GS550L'],
            ['model' => 'GS650G KATANA'],
            ['model' => 'GS650GT'],
            ['model' => 'GS850G'],
            ['model' => 'GS1000'],
            ['model' => 'GS1000C/HC/EC/N/EN/HN'],
            ['model' => 'GS1000G'],
            ['model' => 'GS1000S'],
            ['model' => 'GS1000T/ET/HT'],
            ['model' => 'GS1100'],
            ['model' => 'GSF 400 BANDIT'],
            ['model' => 'GSF 600 BANDIT'],
            ['model' => 'GSF 600S BANDIT'],
            ['model' => 'GSF 650 BANDIT'],
            ['model' => 'GSF 1200 BANDIT'],
            ['model' => 'GSF 1200S BANDIT'],
            ['model' => 'GSF 1250 BANDIT'],
            ['model' => 'GSF 1250S ABS BANDIT'],
            ['model' => 'GSF 1250S BANDIT'],
            ['model' => 'GSR600'],
            ['model' => 'GSR750'],
            ['model' => 'GSR750 ABS'],
            ['model' => 'GSR750Z'],
            ['model' => 'GSR750Z ABS'],
            ['model' => 'GSX-250'],
            ['model' => 'GSX-250 RA'],
            ['model' => 'GSX-400'],
            ['model' => 'GSX-550'],
            ['model' => 'GSX-600F'],
            ['model' => 'GSX-650F'],
            ['model' => 'GSX-750'],
            ['model' => 'GSX-750E'],
            ['model' => 'GSX-750F'],
            ['model' => 'GSX-750S'],
            ['model' => 'GSX-1000S KATANA'],
            ['model' => 'GSX-1100'],
            ['model' => 'GSX-1250F ABS'],
            ['model' => 'GSX-1300 B-KING'],
            ['model' => 'GSX-1300R ABS HAYABUSA'],
            ['model' => 'GSX-1300R HAYABUSA'],
            ['model' => 'GSX-1400'],
            ['model' => 'GSX-R125R/RX'],
            ['model' => 'GSX-R400'],
            ['model' => 'GSX-R600'],
            ['model' => 'GSX-R750'],
            ['model' => 'GSX-R1000'],
            ['model' => 'GSX-R1000R'],
            ['model' => 'GSX-R1100'],
            ['model' => 'GSX-S125 MLX'],
            ['model' => 'GSX-S750A'],
            ['model' => 'GSX-S1000'],
            ['model' => 'GSX-S1000F ABS'],
            ['model' => 'GT200'],
            ['model' => 'GT200E'],
            ['model' => 'GT250'],
            ['model' => 'GT250E'],
            ['model' => 'GW250 INAZUMA'],
            ['model' => 'GZ125 MARAUDER'],
            ['model' => 'LS650 SAVAGE'],
            ['model' => 'LT50'],
            ['model' => 'LT80'],
            ['model' => 'PE175'],
            ['model' => 'PE250'],
            ['model' => 'PE400'],
            ['model' => 'RF600'],
            ['model' => 'RF900'],
            ['model' => 'RG50'],
            ['model' => 'RG50W'],
            ['model' => 'RG125'],
            ['model' => 'RG250'],
            ['model' => 'RG500'],
            ['model' => 'RGV250'],
            ['model' => 'RM-Z250'],
            ['model' => 'RM-Z450'],
            ['model' => 'RM50'],
            ['model' => 'RM80'],
            ['model' => 'RM100'],
            ['model' => 'RM125'],
            ['model' => 'RM250'],
            ['model' => 'RM465'],
            ['model' => 'RM500'],
            ['model' => 'RMX250'],
            ['model' => 'RMX450'],
            ['model' => 'RV50'],
            ['model' => 'RV125 VAN VAN'],
            ['model' => 'SB200'],
            ['model' => 'SB200N'],
            ['model' => 'SFV 650 ABS GLADIUS'],
            ['model' => 'SFV 650 GLADIUS'],
            ['model' => 'SP370'],
            ['model' => 'SV650'],
            ['model' => 'SV650 ABS'],
            ['model' => 'SV650S'],
            ['model' => 'SV1000'],
            ['model' => 'TL1000R'],
            ['model' => 'TL1000S'],
            ['model' => 'TR50S'],
            ['model' => 'TS100'],
            ['model' => 'TS125E'],
            ['model' => 'TS125R'],
            ['model' => 'TS125X'],
            ['model' => 'TS250E'],
            ['model' => 'TS250X'],
            ['model' => 'TU250'],
            ['model' => 'UC125 EPICURO'],
            ['model' => 'UH125'],
            ['model' => 'UH125 ABS BURGMAN'],
            ['model' => 'UH125 BURGMAN'],
            ['model' => 'UH125G BURGMAN'],
            ['model' => 'UH125Z BURGMAN'],
            ['model' => 'UH125ZE BURGMAN'],
            ['model' => 'UH200 ABS BURGMAN'],
            ['model' => 'UH200 BURGMAN'],
            ['model' => 'UH200G BURGMAN'],
            ['model' => 'UK110NE ADDRESS'],
            ['model' => 'UK110NX ADDRESS'],
            ['model' => 'UX50W'],
            ['model' => 'UX50WX'],
            ['model' => 'UX50WY'],
            ['model' => 'UX125K'],
            ['model' => 'UX125K8'],
            ['model' => 'UX150 SIXTEEN'],
            ['model' => 'VL125 INTRUDER'],
            ['model' => 'VL250 INTRUDER'],
            ['model' => 'VL800 INTRUDER'],
            ['model' => 'VL800C INTRUDER'],
            ['model' => 'VL800CUE INTRUDER'],
            ['model' => 'VL1500 INTRUDER'],
            ['model' => 'VL1500BT INTRUDER'],
            ['model' => 'VLR1800 INTRUDER'],
            ['model' => 'VS600'],
            ['model' => 'VS600G'],
            ['model' => 'VS800'],
            ['model' => 'VS1400'],
            ['model' => 'VZ800'],
            ['model' => 'VZ1500'],
            ['model' => 'VZ1600'],
            ['model' => 'VZR1800'],
            ['model' => 'VZR1800 BOULEVARD'],
            ['model' => 'VZR1800BZ BOULEVARD'],
            ['model' => 'XF650 FREEWIND'],
        ];

        if (DB::table('bike_models')->where('brand_name_id', $hondaId)->exists()) {
            return;
        }

        foreach ($bikeModels as $bikeModel) {
            DB::table('bike_models')->insert([
                'brand_name_id' => $hondaId,
                'model' => $bikeModel['model'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
