CREATE TABLE `pcn_case_updates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `case_id` bigint unsigned NOT NULL,
  `update_date` datetime NOT NULL,
  `is_appealed` tinyint(1) DEFAULT '0',
  `is_paid_by_owner` tinyint(1) DEFAULT '0',
  `is_paid_by_keeper` tinyint(1) DEFAULT '0',
  `additional_fee` decimal(10,2) DEFAULT '0.00',
  `picture_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `note` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_transferred` tinyint(1) NOT NULL DEFAULT '0',
  `user_id` bigint unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `is_cancled` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `pcn_case_updates_user_id_foreign` (`user_id`),
  KEY `pcn_case_updates_case_id_foreign` (`case_id`),
  CONSTRAINT `pcn_case_updates_case_id_foreign` FOREIGN KEY (`case_id`) REFERENCES `pcn_cases` (`id`),
  CONSTRAINT `pcn_case_updates_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6158 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
