<?php

namespace Database\Seeders\ProductionData;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContactQueriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Auto-generated from production data.
     * Table: contact_queries
     * Records: 72
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::statement('TRUNCATE TABLE `contact_queries`');
        
        DB::unprepared(<<<'SQL'
INSERT INTO `contact_queries` (`id`, `name`, `email`, `subject`, `phone`, `message`, `is_dealt`, `dealt_by_user_id`, `created_at`, `updated_at`, `notes`) VALUES
('1', 'BASITTEST', 'a.basit.cse@gmail.com', 'TEST', '923183017166', 'TEST', '1', '93', '2025-04-25 17:11:25', '2025-04-25 17:14:44', NULL),
('2', 'TEST', 'support@neguinhomotors.co.uk', 'TEST SUBJECT', '923183017166', 'TESTEST', '1', '109', '2025-04-25 17:12:17', '2025-06-07 12:13:34', NULL),
('3', 'Joanna Riggs', 'joannariggs278@gmail.com', 'Explainer Video for your website?', '3771603127', 'Hi,\r\n\r\nI just visited neguinhomotors.co.uk and wondered if you\'d ever thought about having an engaging video to explain what you do?\r\n\r\nOur videos cost just $195 for a 30 second video ($239 for 60 seconds) and include a full script, voice-over and video.\r\n\r\nI can show you some previous videos we\'ve done if you want me to send some over. Let me know if you\'re interested in seeing samples of our previous work.\r\n\r\nRegards,\r\nJoanna', '1', '109', '2025-04-26 14:21:59', '2025-06-07 12:11:58', 'SPAM'),
('4', 'Jairo pariño', 'patinovolunteering@gmail.com', 'Job mecánico motorcicles', '07417344139', 'Hola estoy interesado para trabajar de mecánico tengo experiencia gracias', '1', '109', '2025-05-01 13:27:10', '2025-06-07 12:50:59', NULL),
('5', 'Diana Cruz', 'dianacruz.mkt@gmail.com', 'Re: neguinhomotors.co.uk - google organic search results', '1201201200', 'Hello neguinhomotors.co.uk,\r\n\r\nAre you struggling to generate quality leads and drive traffic to your website?\r\n\r\nShould you want to hear more about our services and solutions, just say the word.\r\n\r\nWell wishes,\r\nLucy Gordon | Digital Marketing Manager\r\n\r\n\r\n\r\nNote: - If you’re not Interested in our Services, send us  \"opt-out\"', '1', '109', '2025-05-02 18:38:26', '2025-06-07 12:11:20', 'SPAM'),
('6', 'Michael Lowry', 'contactbusinessloanuk@gmail.com', 'Need Funding to Scale Your Business?', '2564876616', 'Hi,\r\n\r\nI was reading through your website and really enjoyed your content. I wanted to ask if you offer the option to publish sponsored articles. I\'d be interested in one that mentions my business loan comparison site, business-loan.uk, and includes a link to it.\r\n\r\nOur comparison tool is completely free to use, and using it does not obligate users to take out a loan. It’s a great resource for anyone who wants to explore what kind of financing they might qualify for.\r\n\r\nThe article could be written so that it would be also relevant to your website and bring value to your audience.\r\n\r\nLet me know if this sounds interesting!\r\n\r\nBest,\r\n\r\nMichael Lowry\r\n\r\nwww.business-loan.uk\r\n\r\ncontactbusinessloanuk@gmail.com', '1', '109', '2025-05-06 20:44:57', '2025-06-07 12:50:06', 'SPAM'),
('7', 'Zenaida Provan', 'bellfrost46078@gmail.com', 'Boost Your Online Presence with SEO and Social Media Solutions!', '7173455498', 'Hello\r\n\r\nAt Your SEO & Digital Marketing Partner, we offer complete SEO and promotion solutions designed to enhance your visibility, traffic, and sales:\r\n\r\n- Google Maps Ranking – Rank higher in local search results.\r\n- YouTube Ranking – Increase your video visibility and audience.\r\n- SEO Backlinks – Gain authority and climb up in Google rankings.\r\n- Website Traffic – Real, targeted, and relevant traffic.\r\n- Content Creation – Optimized articles to drive more organic traffic.\r\n- Social Media Manager – Manage and grow your social media networks for a stronger brand presence.\r\n\r\nWe provide personalized strategies and ongoing support to help you achieve visible, long-term, and measurable results!\r\n\r\nIf you are interested in these services, please reply to this email and we will discuss how we can help you achieve your online goals.\r\n\r\nBest regards,\r\nYour SEO & Digital Marketing Expert\r\n\r\n\r\n \r\n \r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n\r\n\r\n \r\n\r\nUnited States, PA, Littlestown, 17340, 2074 Stout Street\r\nTo stop any further communication from us, please reply to this email with subject: Unsubscribe !neguinhomotors.co.uk', '1', '109', '2025-05-07 09:27:45', '2025-06-07 12:10:40', 'SPAM'),
('8', 'Michael Lowry', 'contactbusinessloanuk@gmail.com', 'Need Funding to Scale Your Business?', '9368296023', 'Hi,\r\n\r\nI was reading through your website and really enjoyed your content. I wanted to ask if you offer the option to publish sponsored articles. I\'d be interested in one that mentions my business loan comparison site, business-loan.uk, and includes a link to it.\r\n\r\nOur comparison tool is completely free to use, and using it does not obligate users to take out a loan. It’s a great resource for anyone who wants to explore what kind of financing they might qualify for.\r\n\r\nThe article could be written so that it would be also relevant to your website and bring value to your audience.\r\n\r\nLet me know if this sounds interesting!\r\n\r\nBest,\r\n\r\nMichael Lowry\r\n\r\nwww.business-loan.uk\r\n\r\ncontactbusinessloanuk@gmail.com', '1', '109', '2025-05-08 07:00:22', '2025-06-07 12:12:14', 'SPAM'),
('9', 'Vernita Mcswain', 'bellfrost46078@gmail.com', 'Boost Your Online Presence with SEO and Social Media Solutions!', '4168887790', 'Hello\r\n\r\nAt Your SEO & Digital Marketing Partner, we offer complete SEO and promotion solutions designed to enhance your visibility, traffic, and sales:\r\n\r\n- Google Maps Ranking – Rank higher in local search results.\r\n- YouTube Ranking – Increase your video visibility and audience.\r\n- SEO Backlinks – Gain authority and climb up in Google rankings.\r\n- Website Traffic – Real, targeted, and relevant traffic.\r\n- Content Creation – Optimized articles to drive more organic traffic.\r\n- Social Media Manager – Manage and grow your social media networks for a stronger brand presence.\r\n\r\nWe provide personalized strategies and ongoing support to help you achieve visible, long-term, and measurable results!\r\n\r\nIf you are interested in these services, please reply to this email and we will discuss how we can help you achieve your online goals.\r\n\r\nBest regards,\r\nYour SEO & Digital Marketing Expert\r\n\r\n\r\n \r\n \r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n\r\n\r\n \r\n\r\nCanada, ON, Toronto, M5t 1t4, 2576 Tycos Dr\r\nTo stop any further communication from us, please reply to this email with subject: Unsubscribe !neguinhomotors.co.uk', '1', '109', '2025-05-10 01:38:05', '2025-06-07 12:10:32', 'SPAM'),
('10', 'Judith Struthers', 'bellfrost46078@gmail.com', 'Boost Your Online Presence with SEO and Social Media Solutions!', '1182876529', 'Hello\r\n\r\nAt Your SEO & Digital Marketing Partner, we offer complete SEO and promotion solutions designed to enhance your visibility, traffic, and sales:\r\n\r\n- Google Maps Ranking – Rank higher in local search results.\r\n- YouTube Ranking – Increase your video visibility and audience.\r\n- SEO Backlinks – Gain authority and climb up in Google rankings.\r\n- Website Traffic – Real, targeted, and relevant traffic.\r\n- Content Creation – Optimized articles to drive more organic traffic.\r\n- Social Media Manager – Manage and grow your social media networks for a stronger brand presence.\r\n\r\nWe provide personalized strategies and ongoing support to help you achieve visible, long-term, and measurable results!\r\n\r\nIf you are interested in these services, please reply to this email and we will discuss how we can help you achieve your online goals.\r\n\r\nBest regards,\r\nYour SEO & Digital Marketing Expert\r\n\r\n\r\n \r\n \r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n\r\n\r\n \r\n\r\nBrazil, SP, Sao Paulo, 02363-255, Rua Mimosa 953\r\nTo stop any further communication from us, please reply to this email with subject: Unsubscribe !neguinhomotors.co.uk', '1', '109', '2025-05-11 02:09:39', '2025-06-07 12:10:23', 'SPAM'),
('11', 'Chastity Mock', 'chastity.mock@outlook.com', 'Get 1,000 Guaranteed Buyer Clicks + $100K in Prizes', '3819164072', 'Hello\r\n\r\nReceive 1,000 guaranteed clicks from verified online buyers—people who’ve already spent money with us. \r\n\r\nPair that with our all-in-one marketing toolkit and unlock serious results fast.\r\n\r\nWant in =>  https://zeep.ly/AUQqm\r\n\r\nBest regards\r\nChastity\r\n\r\n\r\n\r\nTo stop any further communication from us, please reply to this email...', '1', '109', '2025-05-12 00:19:25', '2025-06-07 12:11:02', 'SPAM'),
('12', 'Luciana Atchley', 'bellfrost46078@gmail.com', 'Boost Your Online Presence with SEO and Social Media Solutions!', '2261321085', 'Hello\r\n\r\nAt Your SEO & Digital Marketing Partner, we offer complete SEO and promotion solutions designed to enhance your visibility, traffic, and sales:\r\n\r\n- Google Maps Ranking – Rank higher in local search results.\r\n- YouTube Ranking – Increase your video visibility and audience.\r\n- SEO Backlinks – Gain authority and climb up in Google rankings.\r\n- Website Traffic – Real, targeted, and relevant traffic.\r\n- Content Creation – Optimized articles to drive more organic traffic.\r\n- Social Media Manager – Manage and grow your social media networks for a stronger brand presence.\r\n\r\nWe provide personalized strategies and ongoing support to help you achieve visible, long-term, and measurable results!\r\n\r\nIf you are interested in these services, please reply to this email and we will discuss how we can help you achieve your online goals.\r\n\r\nBest regards,\r\nYour SEO & Digital Marketing Expert\r\n\r\n\r\n \r\n \r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n\r\n\r\n \r\n\r\nGermany, NW, Gummersbach, 51643, Lietzenburger Strasse 74\r\nTo stop any further communication from us, please reply to this email with subject: Unsubscribe !neguinhomotors.co.uk', '1', '109', '2025-05-16 08:25:46', '2025-06-07 12:10:16', 'SPAM'),
('13', 'Bemi Brooks', 'seorankingtech@gmail.com', 'Re: Increase SEO and Driving Online Presence', '1201201200', 'Hello ngnmotors.co.uk,\r\n\r\nAre you facing difficulties in growing your lead generation and boosting website traffic?\r\n\r\nWould you be interested in hearing more about it?\r\n\r\nWell wishes,\r\nBemi Brooks | Digital Marketing Manager\r\n\r\n\r\n\r\nNote: - If you’re not Interested in our Services, send us  \"opt-out\"', '1', '109', '2025-05-17 02:25:32', '2025-06-07 12:11:47', 'SPAM'),
('14', 'Akilah Worthington', 'akilah.worthington@gmail.com', 'Get 1,000 Guaranteed Buyer Clicks + $100K in Prizes', '7345573926', 'Hello\r\n\r\nReceive 1,000 guaranteed clicks from verified online buyers—people who’ve already spent money with us. \r\n\r\nPair that with our all-in-one marketing toolkit and unlock serious results fast.\r\n\r\nWant in =>  https://zeep.ly/AUQqm\r\n\r\nBest regards\r\nAkilah\r\n\r\n\r\n\r\nTo stop any further communication from us, please reply to this email...', '1', '109', '2025-05-18 00:34:11', '2025-06-07 12:10:53', 'SPAM'),
('15', 'William Phrempong', 'William.frimpong01@gmail.com', 'FOR SALE: HONDA FORZA 125', '07512395386', 'I\'m interested in your HONDA FORZA 125.', '1', '109', '2025-05-19 23:33:31', '2025-06-07 12:15:35', 'Tried to call but No response message has been sent by Tahir.'),
('16', 'Aydin', 'aydin12345@hotmail.co.uk', 'Surron Pickup/Delivery', '07724296655', 'Hi,\r\n\r\nWas just wondering how much it\'d be to pick up my 2025 Surron LBX from NG2 4EL and deliver to E4 7PE? Also would this be possible to pick up on Tuesday next week (27th may) and delivery (28th May). I was using another transportation company but they do not have any delivery slots until 2nd of June which is quite a while away. \r\n\r\nKind regards,\r\nAydin', '1', '109', '2025-05-21 16:38:49', '2025-05-28 17:43:27', NULL),
('17', 'Estibaliz Ospina Lopez', 'estibalizospina7@gmail.com', 'FOR SALE: Honda CB125R', '07940473677', 'I\'m interested in your Honda CB125R.', '1', '109', '2025-05-27 15:24:44', '2025-05-28 17:43:17', NULL),
('18', 'Estibaliz Ospina Lopez', 'estibalizospina7@gmail.com', 'FOR SALE: Honda CB125R', '07940473677', 'I\'m interested in your Honda CB125R and the price of it.', '1', '109', '2025-05-27 15:26:45', '2025-05-28 17:40:59', NULL),
('19', 'Bob Williams', 'willirk@hotmail.co.uk', 'FOR SALE: HONDA ADV 350 A-R', '07521913721', 'I\'m interested in your HONDA ADV 350 A-R. Can you email me more info re condition, service history etc. and best price for delivery to Worthing West Sussex BN13 1LH about 50 miles from you. Many thanks.', '1', '109', '2025-05-28 16:43:11', '2025-05-28 22:08:14', NULL),
('20', 'Sami Tamer', 'pfandbriefbank@gmail.com', 'FOR SALE: HONDA ADV 350 A-R', '07480308268', 'I\'m interested in your HONDA ADV 350 A-R. Where can I see the bike? How many owners did it have?', '1', '109', '2025-06-06 14:58:21', '2025-06-07 12:49:48', 'Gustavo already spoke to this customer. Forget to put notes'),
('21', 'Dessie', 'info@coulter.bangeshop.com', 'Dessie Coulter', '3971337071', 'Good Morning, \r\n\r\nI hope this email finds you well. I wanted to let you know about our new BANGE backpacks and sling bags that just released.\r\n\r\nBange is perfect for students, professionals and travelers. The backpacks and sling bags feature a built-in USB charging port, making it easy to charge your devices on the go.  Also they are waterproof and anti-theft design, making it ideal for carrying your valuables.\r\n\r\nBoth bags are made of durable and high-quality materials, and are perfect for everyday use or travel.\r\n\r\nOrder yours now at 50% OFF with FREE Shipping: http://bangeshop.com\r\n\r\nRegards,\r\n\r\nDessie', '1', '109', '2025-06-06 16:04:09', '2025-06-07 12:13:23', 'SPAM'),
('22', 'Kenny Abendroth', 'abendroth.kenny@gmail.com', 'Claim Your $447K AI-Powered Business Today', '7942626838', 'Hello\r\n\r\nClaim Your $447K AI-Powered Business Today\r\n\r\nAccess a fully built, AI-powered business valued at $447K—designed to generate up to $417.95 per sale. No tech skills or hard work required.\r\n\r\nInterested in unlocking this done-for-you income stream?\r\n\r\nWant in =>  https://zeep.ly/AUQqm\r\n\r\nBest regards\r\nKenny\r\n\r\n\r\n\r\nIf you wish to unsubscribe, please reply to this email.', '1', '109', '2025-06-08 16:57:03', '2025-06-11 11:53:17', 'SPAM'),
('23', 'Jerome Danvers', 'jeromedanvers@gmail.com', 'Front brake locked', '07904123370', 'Hi,\r\n\r\nWent to ride to work today and discovered the Front brake has locked up - or at least that\'s what I think has happened.  The back wheel rotates fine but I\'m unable to check if the front wheel moves.\r\n\r\nI rode it home yesterday without issue, today I lubed the chain.  Doesn\'t move in neutral or in 1st gear.  \r\n\r\nAny idea what might be wrong with it and do you do call outs?  I cannot get the bike to you at the mo.\r\n\r\nThanks', '1', '109', '2025-06-10 14:36:19', '2025-06-10 14:48:23', 'Customer wants collection from his address to check front Wheel.'),
('24', 'Kaue rocha', 'kauepaula6969@gmail.com', 'FOR SALE: HONDA ADV 350', '07379328571', 'I\'m interested in your HONDA ADV 350. Do you offer installment payments? I had the same one, but it was stolen this week, and I would like to get another one just like it. I can pay £4500 for it', '1', '109', '2025-06-10 20:48:12', '2025-06-11 11:53:04', 'Tahir contacted this client'),
('25', 'Kaue rocha', 'kauepaula6969@gmail.com', 'FOR SALE: HONDA ADV 350', '07379328571', 'I\'m interested in your HONDA ADV 350. Do you offer installment payments? I had the same one, but it was stolen this week, and I would like to get another one just like it. I can pay £4500 for it', '1', '109', '2025-06-10 20:48:14', '2025-06-11 11:52:56', 'Tahir contacted this client'),
('26', 'Diana Cruz', 'seorankingtech@gmail.com', 'Re: No gimmicks. Just growth. - neguinhomotors.co.uk', '1201201200', 'Dear team, \"neguinhomotors.co.uk\"\r\n\r\nGain 10 to 20 organic clients who are genuinely interested in your services using ethical marketing strategies.\r\n\r\nP.S. I\'d be happy to share more details about our services and solutions if you\'re interested.\r\n\r\n\r\nSincerely,\r\nDiana Cruz | Digital Marketing Manager\r\n\r\n\r\n\r\nNote :  - If you’re not Interested in our Services, send us  \" NO \"', '1', '109', '2025-06-12 08:00:47', '2025-06-16 09:32:57', 'SPAM'),
('27', 'Diana Cruz', 'seorankingtech@gmail.com', 'Re: High-quality leads now - ngnmotors.co.uk', '1201201200', 'Dear team, \"ngnmotors.co.uk\"\r\n\r\nWhat is the biggest challenge that you are currently facing with your website, especially while generating organic leads and traffic?\r\n\r\nP.S. Feel free to let me know if you\'d like to hear more about our services and solutions. \r\n\r\nThanks for your time,\r\nDiana Cruz | Digital Marketing Manager\r\n\r\n\r\n\r\nNote :  - If you’re not Interested in our Services, send us  \" NO \"', '0', NULL, '2025-06-20 09:54:39', '2025-06-20 09:54:39', NULL),
('28', 'Maxie Pogue', 'maxie.pogue@msn.com', 'Thought You’d Appreciate This', '3938985726', 'We’re not here to sell you anything. Just send us your link and we’ll help get your site in front of real people. It’s completely free — because we believe in giving back to the web.\r\nhttps://realwebsitevisitors.my', '0', NULL, '2025-06-22 03:36:53', '2025-06-22 03:36:53', NULL),
('29', 'Linnea', 'info@neguinhomotors.co.uk', 'NGN - Motorcycle Rentals, Repairs, and Motorcycle MOT in London, Catford, and Tooting - Neguinho Motors Ltd', '9045553296', 'Morning \r\n \r\nIs your dog\'s nails getting too long? If you\'re tired of going to the vet or groomer to get them trimmed, why not try PawSafer™? \r\nWith PawSafer™, you can trim your dog\'s nails from the comfort of your own home, and it only takes a few minutes!\r\n\r\nPawSafer™ is the safest and most convenient way to trim your dog\'s nails, and it\'s very affordable. \r\n\r\nGet it while it\'s still 50% OFF + FREE Shipping\r\n\r\nBuy here: https://pawtrim.shop\r\n \r\nKind Regards, \r\n \r\nLinnea', '1', '109', '2025-06-24 09:39:07', '2025-06-24 09:40:16', 'SPAM'),
('30', 'Curt Hayman', 'hayman.curt62@gmail.com', 'Claim Your $447K AI-Powered Business Today', '6999947104', 'Hello\r\n\r\nClaim Your $447K AI-Powered Business Today\r\n\r\nAccess a fully built, AI-powered business valued at $447K—designed to generate up to $417.95 per sale. No tech skills or hard work required.\r\n\r\nInterested in unlocking this done-for-you income stream?\r\n\r\nWant in =>  https://rb.gy/mv6qbh\r\n\r\nBest regards\r\nCurt\r\n\r\n\r\n\r\nIf you wish to unsubscribe, please reply to this email.', '1', '109', '2025-06-27 14:07:47', '2025-06-27 14:13:39', 'SPAM'),
('31', 'Shihara', 'pshihara1@gmail.com', 'FOR SALE: YAMAHA NMAX 125', '07824718696', 'I\'m interested in your YAMAHA NMAX 125.', '0', NULL, '2025-06-28 09:27:00', '2025-06-28 09:27:00', NULL),
('32', 'Lauri', 'info@ngnmotors.co.uk', 'NGN - Motorcycle Rentals, Repairs, and Motorcycle MOT in London, Catford, and Tooting - Neguinho Motors Ltd', '7027193937', 'Hello there \r\n\r\nI wanted to reach out and let you know about our new dog harness. It\'s really easy to put on and take off - in just 2 seconds - and it\'s personalized for each dog. \r\nPlus, we offer a lifetime warranty so you can be sure your pet is always safe and stylish.\r\n\r\nWe\'ve had a lot of success with it so far and I think your dog would love it. \r\n\r\nGet yours today with 50% OFF: https://caredogbest.com\r\n\r\nFREE Shipping - TODAY ONLY! \r\n\r\nThe Best, \r\n\r\nLauri', '0', NULL, '2025-06-30 22:45:04', '2025-06-30 22:45:04', NULL),
('33', 'Piotr Musielak', 'piotr.musielak@data.pl', NULL, '+48501135904', 'I would like to rent a bike/scooter for a week in August and  make a trip to Wales. Only driver and if it is possible a bike bigger than 125 ccm. I have full licence for bikes since 1982. I am EU citizen and do not live in UK', '1', '109', '2025-07-03 19:09:23', '2025-07-04 09:24:28', 'Response has been sent to given email by NGN Catford Tahir.'),
('34', 'Adam Knowlton', 'adam@compliaceservice.solutions', 'Essential compliance fix', '7171979977', 'Hello,\r\n\r\nWe ran a 30-second scan of Neguinhomotors and found:\r\n- No cookie-consent banner detected  \r\n- Privacy-policy link missing/404  \r\n- Accessibility score 68/100 (Lighthouse)\r\n\r\nThese gaps put the site inside the €2–7k GDPR/CPRA fine bracket.\r\nFixing it is painless: our 5-minute kit adds a compliant privacy page, a 2 kB cookie banner, and an a11y toggle.\r\n\r\nSee for more details → complianceservice.solutions\r\n\r\n— Adam @ Compliance Service\r\nsupport@complianceservice.solutions  \r\n\r\n\r\n\r\nReply STOP to unsubscribe', '0', NULL, '2025-07-04 08:08:11', '2025-07-04 08:08:11', NULL),
('35', 'Syed Mukram ali', 'mukram.ali19805@gmail.com', 'FOR SALE: Honda PCX 125', '07427671454', 'I\'m interested in your Honda PCX 125.', '1', '109', '2025-07-09 10:20:55', '2025-08-04 10:00:51', 'C'),
('36', 'Oliver Hatch-barnwell', 'ollyhb@yahoo.co.uk', 'FOR SALE: HONDA SH 125', '07734949476', 'I\'m interested in your HONDA SH 125. Is it still available? Are you able tonsne same the registration number so I can check insurance?.', '0', NULL, '2025-07-12 22:46:49', '2025-07-12 22:46:49', NULL),
('37', 'Wilma Corona', 'corona.wilma@gmail.com', 'I’m Making $245/Day With This Simple Sales Strategy', '7954100645', 'Hello\r\n\r\nI’m Making $245/Day With This Simple Sales Strategy\r\n\r\nI’ve discovered a proven method that helps turn casual clicks into real sales effortlessly. \r\n\r\nThis tool boosts your conversion rates by automating follow-ups and optimizing customer engagement, so you earn more with less work.\r\n\r\nReady to start earning daily? Click here to unlock your sales potential now => https://rb.gy/gk649q\r\n\r\nBest regards\r\nWilma\r\n\r\n\r\n\r\nIf you wish to unsubscribe, please reply to this email.', '1', '101', '2025-07-24 15:46:17', '2025-07-24 17:06:00', 'SPAM'),
('38', 'Efren Moran', 'efren.moran@gmail.com', 'Free 20-Minute Email Funnel Workshop', '6506825779', 'Hey,\r\n\r\nI discovered a 100% free short video that shows how to use email marketing to generate leads on autopilot and make sales without paying for ads.\r\n\r\nIt\'s completely free and takes just a few minutes to watch. I think it could really help if you\'re building an email list.\r\n\r\nYou can watch it here: https://rb.gy/uxe0l2\r\n\r\nBest regards,  \r\nEfren\r\n\r\n          \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nIf you wish to unsubscribe, please reply to this email.', '0', NULL, '2025-07-26 12:53:22', '2025-07-26 12:53:22', NULL),
('39', 'Valeria Gubinelli', 'valeria.gubinelli@cgmitalia.net', 'PROPOSAL OF NEW ITALIAN BRAND HELMETS', '0818131743', 'Dear Sirs,\r\n\r\nI am Valeria Gubinelli, export manager of CGMITALIA Srl. We recently came across your online store and appreciated the structure and professionalism of your business, which caught our attention.\r\n\r\nI would like to briefly introduce you to our company and our products because we believe they could be a good fit for your assortment.\r\n\r\nWe are an Italian company that has been manufacturing and marketing motorbike helmets under the CGM brand since 2004. Our company has more than 250 references (model/colour) of helmets in all categories. Our company\'s strengths are the excellent quality/price ratio, the continuous availability of products, the speed of order processing (within 48 hours), and the very low guaranteed rate (thanks to accurate quality controls).\r\n\r\nYou can consult the catalogue on our website:\r\nhttps://cgmitalia.net/en/download/    \r\n \r\nSocial channels:\r\nwww.instagram.com/cgmitalia.official/ \r\nwww.facebook.com/cgmitalia.official/ \r\nhttps://www.tiktok.com/@cgmitalia.official \r\nhttps://www.youtube.com/@cgmitalia.official \r\n\r\nAre you interested in receiving further information or a commercial proposal?\r\n\r\nIf that sounds interesting, we would be glad to schedule a meeting at EICMA in Milan, in case you are planning to attend.\r\n\r\nI will gladly answer any questions you may have and remain at your disposal.', '0', NULL, '2025-07-28 11:47:28', '2025-07-28 11:47:28', NULL),
('40', 'Shaunte Throssell', 'shaunte.throssell71@gmail.com', 'Automate Your Sales – No Ads Needed', '8605376557', 'Hi,\r\n\r\nJust came across a FREE short video that teaches how to use automated email systems to generate leads on autopilot and increase conversions without paying for ads.\r\n\r\nIt\'s completely free and takes just around 20 minutes to watch. I think it could be useful if you\'re using email marketing.\r\n\r\nYou can watch it here: https://rb.gy/uxe0l2\r\n\r\nWishing you success,  \r\nShaunte\r\n\r\n          \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nIf you wish to unsubscribe, please reply to this email.', '1', '109', '2025-07-30 10:24:11', '2025-08-04 10:00:32', 'SPAM'),
('41', 'Mathias', 'info@ngnmotors.co.uk', 'NGN - Motorcycle Rentals, Repairs, and Motorcycle MOT in London, Catford, and Tooting - Neguinho Motors Ltd', '9182529840', 'Hello \r\n\r\nI wanted to reach out and let you know about our new dog harness. It\'s really easy to put on and take off - in just 2 seconds - and it\'s personalized for each dog. \r\nPlus, we offer a lifetime warranty so you can be sure your pet is always safe and stylish.\r\n\r\nWe\'ve had a lot of success with it so far and I think your dog would love it. \r\n\r\nGet yours today with 50% OFF:  https://caredogbest.com\r\n\r\nFREE Shipping - TODAY ONLY! \r\n\r\nHave a great time, \r\n\r\nMathias', '1', '109', '2025-07-30 22:37:52', '2025-08-04 10:00:17', 'SPAM'),
('42', 'Hamed Moslehi', 'h.moslehi.h@gmail.com', 'Request for Insurance Documents to Activate Uber Eats Account', '07404409232', 'Hi, I’m planning to work with a rental scooter for food delivery, and I’m trying to open my Uber Eats account.\r\n\r\nI’d like to ask: what insurance document do I need to upload to get my Uber account approved?\r\n\r\nDo you provide the insurance and vehicle documents in advance so I can upload them before renting the scooter? Since the Uber activation takes time, I want to finish that first and then rent the scooter and start working.\r\n\r\nThanks!', '0', NULL, '2025-08-01 11:44:32', '2025-08-01 11:44:32', NULL),
('43', 'Reuben Lindo', 'Lindotm@aol.com', 'FOR SALE: YAMAHA X-MAX 125', '07887882939', 'I\'m interested in your YAMAHA X-MAX 125.', '1', '109', '2025-08-03 17:42:38', '2025-08-04 09:59:29', 'I\'ve sent whatsapp message to this client with best available option.\r\nTahir'),
('44', 'Bert Hutchens', 'hutchens.bert@gmail.com', 'I’m Making $245/Day With This Simple Sales Strategy', '7913147245', 'Hello\r\n\r\nI’m Making $245/Day With This Simple Sales Strategy\r\n\r\nI’ve discovered a proven method that helps turn casual clicks into real sales effortlessly. \r\n\r\nThis tool boosts your conversion rates by automating follow-ups and optimizing customer engagement, so you earn more with less work.\r\n\r\nReady to start earning daily? Click here to unlock your sales potential now => https://rb.gy/gk649q\r\n\r\nBest regards\r\nBert\r\n\r\n\r\n\r\nIf you wish to unsubscribe, please reply to this email.', '0', NULL, '2025-08-06 00:30:02', '2025-08-06 00:30:02', NULL),
('45', 'Sasikiran Kumar Sindhanaikani', 'sasikirankumarsindhanaikani@gmail.com', 'Application for Motorcycle Mechanic Role with Sponsorship', '07909328190', 'Dear Neguinho Motors Team,\r\n\r\nI am an Automotive Engineer with hands-on experience in car mechanics through internships. I am very interested in joining your team as a Motorcycle Mechanic.\r\n\r\nAlthough I have not worked with bikes professionally yet, I am a quick learner, highly motivated, and very passionate about practical mechanical work. I am fully willing to relocate close to your workshop in London and commit long-term to the role if visa sponsorship can be provided.\r\n\r\nThank you for considering my application. I would appreciate the opportunity to learn and grow with your team.\r\n\r\nBest regards,\r\nSasikiran Kumar Sindhanaikani\r\nsasikirankumarsindhanaikani@gmail.com\r\n+44 7909 328190', '0', NULL, '2025-08-07 00:46:11', '2025-08-07 00:46:11', NULL),
('46', 'Marcos Meconi', 'marcosmeconni0570@gmail.com', 'FOR SALE: Honda CB125F', '07932794648', 'Preciso trocar minha moto tenho uma Cbf 2017 gostaria de pagar uma dessa semanalmente e dando a minha de entrada tem como ?', '0', NULL, '2025-08-08 15:51:06', '2025-08-08 15:51:06', NULL),
('47', 'Terry Fowler', 'pageranktechnology@gmail.com', 'Re: SEO Assistance', '1234567890', 'Hello team,\r\n\r\nWant more leads and better Google rankings? I’ve helped others do it—happy to help you too.\r\n\r\nAre you interested in gaining more information about it?\r\n\r\n\r\nWell wishes,\r\nTerry Fowler | Digital Marketing Manager\r\n\r\n\r\n\r\nWebsite : http://www.neguinhomotors.co.uk/', '1', '109', '2025-08-17 10:55:42', '2025-08-18 09:27:01', 'SPAM'),
('48', 'Saeed', 'saeedalf187@gmail.com', 'FOR SALE: YAMAHA NMAX 125', '07988314515', 'I\'m interested in your YAMAHA NMAX 125.', '0', NULL, '2025-08-23 00:00:25', '2025-08-23 00:00:25', NULL),
('49', 'Saeed', 'saeedalf187@gmail.com', 'FOR SALE: YAMAHA NMAX 125', '07988314515', 'I\'m interested in your YAMAHA NMAX 125.', '0', NULL, '2025-08-23 00:00:26', '2025-08-23 00:00:26', NULL),
('50', 'Philip', 'philip@mulcahyfamily.org', 'estimate for replacement (including fitting) of stolen parts on a 2023 NT1100.', '07816936290', 'https://photos.app.goo.gl/UMrjySiCuWBHGJxG6 links to a picture of my bike after some nasty people removed (presumably because someone else has had a prang) various plastic parts from the left front of my Honda NT1100 (2022 version, manually geared), including the indicator.\r\n\r\nYour Catford base is interesting to me, because I don\'t want to ride the machine too far without an indicator.\r\n\r\nYours,\r\n\r\nPhilip', '0', NULL, '2025-08-25 16:53:29', '2025-08-25 16:53:29', NULL),
('51', 'Philip', 'philip@mulcahyfamily.org', 'estimate for replacement (including fitting) of stolen parts on a 2023 NT1100.', '07816936290', 'https://photos.app.goo.gl/UMrjySiCuWBHGJxG6 links to a picture of my bike after some nasty people removed (presumably because someone else has had a prang) various plastic parts from the left front of my Honda NT1100 (2022 version, manually geared), including the indicator.\r\n\r\nYour Catford base is interesting to me, because I don\'t want to ride the machine too far without an indicator.\r\n\r\nYours,\r\n\r\nPhilip', '0', NULL, '2025-08-25 16:54:24', '2025-08-25 16:54:24', NULL),
('52', 'Jeneil', 'jeneilkiaran@gmail.com', 'FOR SALE: Honda CB125R', '07762-35512', 'I\'m interested in your Honda CB125R.', '0', NULL, '2025-08-29 06:05:29', '2025-08-29 06:05:29', NULL),
('53', 'Mohamed', 'mohusstlb845@gmail.com', 'FOR SALE: YAMAHA NMAX 125', '07708757112', 'I\'m interested in your YAMAHA NMAX 125.', '1', '109', '2025-08-31 17:54:18', '2025-09-01 09:45:15', 'TAHIR Send him message on Whatsapp.'),
('54', 'Syed Waseem', 'syedwaseem6969@gmail.com', 'FOR SALE: YAMAHA NMAX 125', '07826085554', 'I\'m interested in your YAMAHA NMAX 125.', '0', NULL, '2025-09-04 22:09:15', '2025-09-04 22:09:15', NULL),
('55', 'Justina Applebaum', 'justina.applebaum@yahoo.com', '$245 a Day: The Simple Strategy That Works', '3818695215', 'Hello\r\n\r\nI learned about a proven way which helps change casual clicks to real sales easily.\r\n\r\nThis system enhances conversion numbers with automated follow-ups while optimizing client engagement, so you make more with less effort.\r\n\r\nReady to make money daily? Click here to unleash your sales power now => https://rb.gy/hy6nmw\r\n\r\nBest regards\r\nJustina\r\n\r\n\r\n\r\nIf you wish to unsubscribe, please reply to this email.', '0', NULL, '2025-09-04 22:27:54', '2025-09-04 22:27:54', NULL),
('56', 'Benjamin', 'benjamin.garcia@hotmail.co.uk', 'Motorbike Hire Inquiry', '07906769545', 'Dear Sir/Madam,\r\n\r\nI’m looking to hire a 125 cc geared motorbike for the day on Monday 8th September. Do you have any availability please?\r\n\r\nRegards,\r\n\r\nBenjamin', '0', NULL, '2025-09-05 14:37:57', '2025-09-05 14:37:57', NULL),
('57', 'Lee Manzi', 'leehotshot64@hotmail.co.uk', 'Repairs', '07514537223', 'Are you able to fit an off side Wing mirror and a Front Mudguard in Black to my 2014 Yamaha delight 114 if I can source the parts ? Many thanks for your time .', '1', '109', '2025-09-05 19:57:42', '2025-09-06 09:05:54', 'TAHIR SENT MESSAGE ON WHATSAPP'),
('58', 'Marko Ivezic', 'markoivezic419@gmail.com', 'FOR SALE: SUZUKI UK 110 NE L6', '07591178963', 'I\'m interested in your SUZUKI UK 110 NE L6.', '0', NULL, '2025-09-09 13:56:58', '2025-09-09 13:56:58', NULL),
('59', 'Kevin Liang', 'joyeenutritionwise@163.com', 'Motorcycle Rental Inquiry for September', '+44 7519078379', 'Dear NG NEGUINHO Team,\r\n\r\nI hope this message finds you well.\r\n\r\nMy name is Kevin, and I am from China. I hold a Hong Kong driving license with a motorcycle (tricycle) endorsement., but no IDP. I will be traveling in the UK for 10 days, arriving in London around September 20, and I would like to rent a motorcycle from your company for about 7 days.\r\n\r\nI came across your website and really liked the motorcycles you offer. Before making a booking, I would like to clarify a few things:\r\n\r\nWith my current Hong Kong license, do I need any additional documentation to be eligible to rent and ride in the UK?\r\n\r\nIf I rent a motorcycle for one week, what additional costs should I expect besides the rental fee (e.g., deposit, insurance, mileage charges)?\r\n\r\nDo I need to purchase extra insurance coverage, or is it already included?\r\n\r\nCould you please let me know the next steps if I’d like to proceed with a reservation?\r\n\r\nThank you very much for your assistance, and I look forward to your reply.\r\n\r\nBest regards,\r\nKevin', '0', NULL, '2025-09-19 05:15:40', '2025-09-19 05:15:40', NULL),
('60', 'Roosevelt', 'info@neguinhomotors.co.uk', 'NGN - Motorcycle Rentals, Repairs, and Motorcycle MOT in London, Catford, and Tooting - Neguinho Motors Ltd', '3165261836', 'Good Morning \r\n\r\nLooking to improve your posture and live a healthier life? Our Medico Postura™ Body Posture Corrector is here to help!\r\n\r\nExperience instant posture improvement with Medico Postura™. This easy-to-use device can be worn anywhere, anytime – at home, work, or even while you sleep.\r\n\r\nMade from lightweight, breathable fabric, it ensures comfort all day long.\r\n\r\nGrab it today at a fantastic 60% OFF: https://medicopostura.com\r\n\r\nPlus, enjoy FREE shipping for today only!\r\n\r\nDon\'t miss out on this amazing deal. Get yours now and start transforming your posture!\r\n\r\nSincerely, \r\n\r\nRoosevelt', '0', NULL, '2025-09-19 20:37:24', '2025-09-19 20:37:24', NULL),
('61', 'Louisa Boudreau', 'bellfrost46078@gmail.com', 'To the Manager of neguinhomotors.co.uk', '7736714439', 'Hello\r\n\r\nThis message is intended for the administrator of neguinhomotors.co.uk. If you are not the person responsible for managing the site, please redirect this email to the right contact.\r\n\r\nOur agency that provides professional SEO services. We can help your website gain more visibility online and get more customers. Here are some of the services we offer:\r\n\r\n - Search Engine Ranking Boost\r\n - Local SEO (Maps)\r\n - YouTube Video Ranking\r\n - Authority Link Building\r\n - Targeted Traffic Services\r\n - SEO-Optimized Articles\r\n - Engaging Video Content\r\n - Full Social Media Management\r\n - Targeted Lead Acquisition\r\n - SEO Outsourcing Solutions\r\n\r\nIf you are the administrator, we would be happy to provide more details and explore how we can help your business in achieving better rankings and customer growth.\r\n\r\nJust get back to us and we’ll suggest the ideal SEO plan for your needs.\r\n\r\nBest regards,\r\nYour SEO & Digital Marketing Expert\r\n\r\n\r\n \r\n \r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n\r\n\r\n \r\n\r\nUnited Kingdom, NA, Nyadd, Fk9 5jy, 38 Abbey Row\r\nTo stop any further communication from us, please reply to this email with subject: Unsubscribe !neguinhomotors.co.uk', '0', NULL, '2025-09-21 12:27:28', '2025-09-21 12:27:28', NULL),
('62', 'Rena Swett', 'rena.swett@gmail.com', 'Transform your smartphone into a $100 per day money maker', '7846711335', 'Hello\r\n\r\nMake your phone work like a $100/day income stream\r\n\r\nI pocket $100+ just by emailing with *Email Cash Machine* — plug-and-play email templates, complimentary autoresponder, exclusive affiliate deals inside. No product creation, no ads, no experience needed. Get paid anywhere from your phone or laptop.\r\n\r\nGrab your lifetime access now for just $seventeen dollars — risk-free with 180-day refund ==> https://rb.gy/uxe0l2\r\n\r\nBest regards\r\nRena\r\n\r\n\r\n\r\nIf you wish to unsubscribe, please reply to this email.', '0', NULL, '2025-10-03 14:40:20', '2025-10-03 14:40:20', NULL),
('63', 'Jerri Hines', 'bellfrost46078@gmail.com', 'Something might be wrong with your website...', '4313577896', 'Hi, I noticed a few issues on your website neguinhomotors.co.uk\r\n\r\nWould you like me to show you what they are?', '0', NULL, '2025-10-06 21:07:11', '2025-10-06 21:07:11', NULL),
('64', 'Rocco', 'rocco01082008@icloud.com', 'Bike needs to be checked', '07432253782', 'Hello, I’ve recently purchased a bike from you lot a Honda vision 110, someone has tried to rob my bike, they have not managed to take it however they have broken it and cut some wires trying to, I’ve managed to get the bike up and running again, am I able to bring it down tommorow at around 2-3pm for it to be checked over, also have you got any spare plastic parts as they have snapped them trying to steal it, thank you', '0', NULL, '2025-10-30 16:40:38', '2025-10-30 16:40:38', NULL),
('65', 'Samir', 'samirchaaraoui1996@hotmail.com', 'FOR SALE: Honda FORZA 350', '07943614693', 'I\'m interested in your Honda FORZA 350.', '0', NULL, '2025-11-06 13:14:14', '2025-11-06 13:14:14', NULL),
('66', 'Jeet', 'sonijeet13@gmail.com', 'FOR SALE: HONDA PCX 125', '07365854671', 'I\'m interested in your HONDA PCX 125.', '1', '127', '2025-11-27 02:17:34', '2025-11-27 10:21:52', NULL),
('67', 'Webike Japan Wholesale Team', 'ws_apply@webike.net', 'Do you carry Japanese motorcycle parts?', '0459604033', 'Hello,\r\n\r\nThis is the Webike Japan Wholesale Team.\r\n\r\nNeed Japanese motorcycle parts fast, in small quantities, and at wholesale prices?\r\n\r\nWebike Japan is Japan’s largest online sourcing platform for motorcycle parts —\r\n4,000+ brands / 3,000,000+ SKUs / OEM & aftermarket / vintage to latest models.\r\n\r\nFor over 15 years, we have been providing retail and wholesale (for motorcycle-related businesses) services from Japan to customers worldwide. Why not consider us as your new supplier?\r\n\r\n[Why shops choose us?]\r\n- No MOQ — wholesale price even from 1 piece\r\n- No registration or monthly fees\r\n- Stock visibility + instant shipping cost calculation\r\n- Fast shipping – 2–3 days to the United Kingdom\r\n- Up to 35% OFF Webike retail price\r\n- Major payment methods supported\r\n\r\n[Bonus for new members]\r\nYou will receive 10,000 Webike Points (1 pt = 1 JPY, approx. 48 GBP total)\r\n\r\nSign up → Get 10,000 pts → Place your first order with immediate discount.\r\n\r\nApplication takes 5 minutes, approval within 1 business day:\r\nhttps://japan.webike.net/wholesale_applyform/\r\n\r\nEven if you already have suppliers, we are perfect as a backup sourcing channel for urgent restocks or niche parts.\r\n\r\nLet us help you secure Japanese parts faster and with better pricing.\r\nIf you have any questions, feel free to reply anytime.\r\n\r\nBest regards,\r\nWebike Japan Wholesale Team', '1', '109', '2025-12-09 07:19:25', '2025-12-09 14:24:36', NULL),
('68', 'Monis Latif', 'xess2monis@gmail.com', 'FOR SALE: HONDA CB 500 F', '07990685925', 'I\'m interested in your HONDA CB 500 F. I have my a2 soon and think it would be a nice first bike.', '1', '127', '2025-12-12 00:50:42', '2025-12-12 09:12:30', NULL),
('69', 'Kerrie', 'sales@ngnmotors.co.uk', 'Kerrie Chavez', '8161513523', 'Hi there \r\n\r\nI wanted to reach out and let you know about our new dog harness. It\'s really easy to put on and take off - in just 2 seconds - and it\'s personalized for each dog. \r\nPlus, we offer a lifetime warranty so you can be sure your pet is always safe and stylish.\r\n\r\nWe\'ve had a lot of success with it so far and I think your dog would love it. \r\n\r\nGet yours today with 50% OFF: https://caredogbest.com\r\n\r\nFREE Shipping - TODAY ONLY! \r\n\r\nCheers, \r\n\r\nKerrie', '1', '122', '2026-01-10 11:41:57', '2026-01-10 12:27:34', NULL),
('70', 'Oliver Kim', 'oliver@alfareviews.com', 'We Offer Professional Review Services', '+447575802542', 'Get positive reviews to boost your Business reputation.\r\n90% of new customers rely on reviews fresh 5-star feedback helps them choose you faster.\r\n\r\nWe provide reviews on Google, Yelp, TripAdvisor, TrustPilot, Glassdoor, Facebook, and more.\r\n\r\nReach out Email: oliver@alfareviews.com\r\nWhatsApp Link: https://wa.me/447575802542', '0', NULL, '2026-01-12 15:57:18', '2026-01-12 15:57:18', NULL),
('71', 'Victor dmore', 'Victordmore9@gmail.com', 'FOR SALE: YAMAHA NMAX 125', '07951 337634', 'I\'m interested in your YAMAHA NMAX 125.', '0', NULL, '2026-01-18 19:28:58', '2026-01-18 19:28:58', NULL),
('72', 'Testing', 'dtahirshakoor@gmail.com', 'FOR SALE: YAMAHA GPD125-A NMAX 125 ABS', '7946848097', 'I\'m interested in your YAMAHA GPD125-A NMAX 125 ABS.', '1', '122', '2026-01-22 19:21:25', '2026-01-24 16:08:25', NULL);
SQL
        );
        
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
}
