<?php

namespace Database\Seeders\ProductionData;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MotorbikeRepairObservationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Auto-generated from production data.
     * Table: motorbike_repair_observations
     * Records: 38
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::statement('TRUNCATE TABLE `motorbike_repair_observations`');
        
        DB::unprepared(<<<'SQL'
INSERT INTO `motorbike_repair_observations` (`id`, `motorbike_repair_id`, `observation_description`, `created_at`, `updated_at`) VALUES
('4', '39', 'The tires are not okay you need to change it after 500 miles', '2025-02-28 22:27:12', '2025-02-28 22:27:12'),
('16', '51', 'Vehicle is ready for collection after test drive by Luiz.', '2025-03-03 12:32:15', '2025-03-03 12:32:15'),
('21', '60', 'Right after the customer left with the motorcycle, he came back saying that the engine light came on. I (Gustavo) told him that it was due to the service performed and that in 2 to 3 days the light would go out. If it didn\'t go out, I told him to go back to the workshop and we would diagnose it with our computer.', '2025-03-15 11:03:43', '2025-03-15 11:03:43'),
('26', '56', 'The customer came and replaced the missing rollers and slides', '2025-03-15 12:08:05', '2025-03-15 12:08:05'),
('28', '62', '15/03 The service was done but we didn\'t have the spark plugs in stock, we ordered and the parts arrived today, he brought the bike to change\r\nAll ready', '2025-03-15 13:01:39', '2025-03-15 13:01:39'),
('32', '65', 'Notes: The indicator buttons is broken, but working \r\n\r\n\r\n MOT £29.65 - MOT PAID RECEIPT 1052\r\n\r\nFor pass in MOT need fixe the following things:\r\n\r\n-Left indicator not working\r\n-Horn is not Working\r\n-Light of the plate is not working\r\n\r\n\r\nPrices: \r\n-If is only new horn, only £25 \r\n-We don\'t have that light plate, if is only eletric problem £30 \r\n-If we have and if is only the left light indicator £10, if the problem is in the indicator need change the both indicator,\r\nwe have only oxford indicator EL337(£20) price only the parts plus £30 for fixe \r\n\r\n\r\n\r\nThe customer will leave the bike for fixe the problem  and make MOT for tomorrow 18/03/2025\r\n\r\nPlease confirm this message, if you agree!\r\n\r\nGustavo', '2025-03-18 17:57:14', '2025-03-18 17:57:14'),
('33', '65', 'After inspecting your motorcycle, we have identified the following issues:\r\n\r\nIndicator Light: The indicator light is LED, and due to its design, it cannot be repaired and will need to be replaced with a new one.\r\n\r\nHorn : The issue lies with the horn, which needs to be replaced. The cost of the new part is £15, and the installation is £10.\r\n\r\nLicense Plate Light: The LED license plate light is damaged and requires replacement. Unfortunately, we do not have an identical or original part. However, we can replace the lamp holder for the plate, which will allow it to function correctly and pass the MOT.\r\n\r\nSummary of parts and services required:\r\n\r\nReplacement of the indicator light (LED) - Parts £20 and labour £30\r\nReplacement of the horn – Part: £15, Installation: £10\r\nReplacement of the license plate light – Replacement of the lamp holder - for a normal light (not led) with suport - £30 \r\n\r\nTotal estimated cost:  £105\r\n\r\nPlease confirm if you authorize the replacement of all the parts and services mentioned so we can proceed with the work.\r\n\r\nWe look forward to your confirmation.', '2025-03-18 17:57:14', '2025-03-18 17:57:14'),
('34', '66', 'PARTS NOT IN STOCK, THERE IS A 4 WEEKS WAIT FOR THEM.', '2025-03-20 13:31:30', '2025-03-20 13:31:30'),
('35', '64', 'Service Report - Customer\'s Motorcycle\r\n\r\nDate of Arrival: 17/03 at 18:15\r\n\r\nCustomer\'s Request : The customer reported the following issues with the motorcycle:\r\n\r\nOil Change and Rear Brake Light Bulb Replacement : The customer requested an oil change and replacement of the rear brake light bulb.\r\n\r\nStarting Issue: The customer mentioned that the motorcycle is not starting after hitting a curb with the jack. Some wires were broken due to the impact, which seems to be causing the starting issue.\r\n\r\nEngine Stalling : The customer noted that when the motorcycle was parked, the engine stopped running. This issue needs to be investigated.\r\n\r\nMOT Test : The customer also requested the motorcycle to be checked for the MOT (mandatory vehicle inspection in the UK) to ensure it passes the inspection.\r\n\r\nCondition of the Motorcycle Upon Arrival : Upon arrival at the workshop on 17/03 at 18:15, the motorcycle was not starting and displayed visible defects in certain parts. The customer also provided a video showing the condition of the motorcycle when it was delivered.\r\n\r\nInitial Actions Required :\r\n\r\nAttempt to Start the Motorcycle : First, we will attempt to start the motorcycle to assess the cause of the starting issue.\r\n\r\nElectrical Inspection: If the problem is related to the electrical system, a full inspection of the wiring and components will be necessary. This electrical inspection will be charged separately at a rate of £80 to thoroughly check the motorcycle and identify any issues with wires or electrical components.\r\n\r\nMOT Checklist : After checking the motorcycle\'s functionality, a detailed checklist will be performed to ensure the motorcycle meets the requirements to pass the MOT. This will include checking essential components such as lighting system, brakes, tires, and other necessary items.\r\n\r\nAgreement with the Customer:\r\n\r\nThe customer has been informed that the initial diagnosis of the motorcycle will proceed as described above. The electrical inspection fee of £80 will apply, and the MOT checklist will be performed afterward. The customer is aware that we cannot guarantee the motorcycle will be ready for pickup on 18/03, as it will depend on the assessment and any necessary repairs.\r\n\r\nThe customer has confirmed that they agree with the outlined procedures and has authorized the start of the work.\r\n\r\nConfirm this message if you agree with the services\r\n\r\nLet me know if you need any further adjustments!', '2025-03-25 17:21:46', '2025-03-25 17:21:46'),
('37', '58', 'During the Basic service inspection, it was noted that the Rear Brake Pads are worn and require replacement.\r\nEBC Brake Pads – £25\r\nYamaha Brake Pads – £35', '2025-03-27 16:41:09', '2025-03-27 16:41:09'),
('38', '53', 'Mechanics managed to start your vehicle; however, a significant noise was coming from the engine. A video of the issue was shared with you for reference.\r\n\r\nTo investigate further, we dismantled the clutch, variator, and belt kit to check for any additional damage. During the inspection, we found that the Kit Belt and Air Filter needed replacement.\r\n\r\nAfter receiving your confirmation, we replaced the necessary components. The vehicle was then reassembled and left running for 30 minutes to ensure everything was functioning correctly.\r\n\r\nPlease drive a maximum of 300 miles and then bring the vehicle back to us for a follow-up inspection. At that stage, we will also check the coolant to ensure the water pump is in good condition.', '2025-03-27 16:41:44', '2025-03-27 16:41:44'),
('41', '68', 'During the service, mechanic Luiz reported that several lights on the motorcycle are not working (burnt out). Additionally, the bike is showing starting issues. The mechanic is currently diagnosing the root cause of the problem.', '2025-03-29 12:54:03', '2025-03-29 12:54:03'),
('45', '59', '-', '2025-04-01 14:40:53', '2025-04-01 14:40:53'),
('51', '79', 'WILLIAN FRIEND', '2025-04-04 11:21:44', '2025-04-04 11:21:44'),
('52', '78', 'CLAIM', '2025-04-04 11:22:07', '2025-04-04 11:22:07'),
('53', '76', 'READY TO SALE OR RENTAL', '2025-04-04 11:22:57', '2025-04-04 11:22:57'),
('54', '72', 'Mechanic is fixing the bike', '2025-04-04 11:24:57', '2025-04-04 11:24:57'),
('55', '72', 'Only the key cover remains', '2025-04-04 11:24:57', '2025-04-04 11:24:57'),
('63', '93', 'We have inspected the head bearings and fork oil both are currently in good condition. The handlebar has been tightened for now. However, if the noise returns, the head bearings may require replacement.', '2025-04-11 16:38:52', '2025-04-11 16:38:52'),
('74', '95', 'Dear Customer,\r\nThe front wheel is currently making contact with the inner fender. There is a possibility that the yoke or forks may be bent. However, we will need to dismantle and inspect it thoroughly to confirm the exact cause of the issue and determine why the tyre is making contact.', '2025-04-16 16:39:36', '2025-04-16 16:39:36'),
('79', '108', 'After checking your bike we\'ve noticed a water leak from Radiator and 2 Seal that need replacement. You need to change Radiator and Seal to proceed further.', '2025-04-29 17:27:09', '2025-04-29 17:27:09'),
('80', '67', 'During maintenance on the front braking system, specifically while cleaning the calliper, it was found that the calliper bolts were severely seized and could not be removed using standard tools.\r\n\r\nActions Taken:\r\nAdditional force and specific techniques were required to release the bolts, which demanded extra time and care to avoid damage to surrounding components. Once removed, the bolts were replaced with two new ones.\r\n\r\nFurthermore, upon inspection of the braking components, it was identified that the front brake pads were completely worn out and required immediate replacement to ensure the vehicle\'s safety.\r\n\r\nNotes:\r\nWe recommend regular maintenance and checks of the braking system, including the condition of pads and bolt fittings, to avoid excessive wear and more complex repairs in the future.', '2025-04-29 17:30:51', '2025-04-29 17:30:51'),
('81', '61', '15/03 - 11:45 start the job - The service will take 2 to 3 hours, the mechanics (neto and cleiton) said because it is a Piaggio Beverly and all the fairings have to be opened to install the alarm and tracker.', '2025-04-29 17:32:08', '2025-04-29 17:32:08'),
('82', '88', 'Firstly, we recharged the battery and carried out the necessary checks in an attempt to start the vehicle. Unfortunately, it was necessary to open the right-hand side of the bike for further inspection. Upon doing so, we discovered that the generator connector was heavily covered in dust.\r\n\r\nWe disconnected and thoroughly cleaned the connector, which allowed us to start the bike successfully. However, a loud and concerning noise was coming from the engine. Based on our assessment, this indicates internal damage which will require a full engine rebuild to resolve.', '2025-04-29 17:33:39', '2025-04-29 17:33:39'),
('83', '105', 'We\'ve checked your Spark plug, V-Belt & Clutch. Everything seems good for now. Rear tyre is not original on this bike.', '2025-04-29 17:34:13', '2025-04-29 17:34:13'),
('85', '94', 'Just to Let you know all the USED Parts(Second Hand Parts) Has no warranty or guarantee.', '2025-05-03 15:56:01', '2025-05-03 15:56:01'),
('86', '57', 'No work was done by NGN. We just charge Storage Charges to Third Party Insurance company.', '2025-05-05 17:27:35', '2025-05-05 17:27:35'),
('87', '121', 'Just to Let you know we charge £55 Per Hour for Labour. It\'ll Probably take 2 hours to finish this job. \r\nPlease note, this list has been supplied by customer and does not represent work carried out or parts identified for replacement by Neguinho Motors Ltd.', '2025-05-07 15:37:15', '2025-05-07 15:37:15'),
('89', '124', 'We have inspected your vehicle and found that the connector between the generator and the ECU is burnt.\r\n\r\nTo resolve this issue, there are two options:\r\n\r\nReplace the entire wiring harness, as the connector is not available separately.\r\n\r\nRemove the damaged connector and make direct cable connections.\r\n\r\nFollowing our phone conversation, you have chosen to proceed with the second option removing the connector and establishing direct connections in the wiring. The cost for this work will be £80 labour .', '2025-05-28 11:14:39', '2025-05-28 11:14:39'),
('90', '127', 'Chain and Sprockets: Not in optimal condition Recommend monitoring closely and replacing soon to maintain safe and smooth Driving.\r\n\r\nTyres: Tread depth is low. Tyres are not in good condition, replacement is advised to ensure road safety and compliance.', '2025-06-09 12:48:05', '2025-06-09 12:48:05'),
('92', '132', 'At the moment, we’ve tightened the head bearings.\r\nIf the issue happens again, the bearings will need to be replaced.', '2025-06-23 16:46:55', '2025-06-23 16:46:55'),
('93', '133', 'The mechanic has inspected your bike and found that one screw was missing from the front brake calliper, which has now been replaced.', '2025-06-24 13:37:53', '2025-06-24 13:37:53'),
('95', '139', 'As per our inspection, the Variator needs to be replaced. The clutch pulley is stuck and has a crack on one side. These parts should be changed as soon as possible; if not, it will affect the belt, causing it to wear out much quicker than expected.', '2025-07-29 17:39:05', '2025-07-29 17:39:05'),
('96', '140', 'manifold carburetor from your bike is damage, so we are checking if the problem is only in the manifold or the complete carbureto', '2025-08-02 12:46:09', '2025-08-02 12:46:09'),
('97', '140', 'We discussed with the customer that we were unable to purchase the original carburetor because we called the company that manufactures this model and they only have a re-spec for these parts for October or November, so the best choice was to find a carburetor as similar as possible for the customer to buy and bring it to us to install on his motorcycle.', '2025-08-02 12:46:09', '2025-08-02 12:46:09'),
('98', '140', '02/08/2025 - I send the link from  the new carburetor for his bike', '2025-08-02 12:46:09', '2025-08-02 12:46:09'),
('99', '141', 'The motorcycle license plate will only be made when the customer brings the v5 document and the driving license from Liciense', '2025-08-02 14:06:24', '2025-08-02 14:06:24'),
('101', '153', 'Mechanic found a loose battery screw.  \r\nThe Rear brake pads were heavily rusted, so these have been replaced. Rear Brake Caliper Rubber needs replacement which have already ordered. A minor left-side oil leak was noted but is not dangerous. We\'ve cleaned your Kill Switch with WD-40 and Greece. The clutch and gear pedal were also adjusted.', '2025-11-15 17:38:41', '2025-11-15 17:38:41');
SQL
        );
        
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
}
